import { NextResponse } from "next/server";

const contractsPayload = {
    title: "Latest Contracts Post",
    description: "Search and connect with the right companies faster",
    categories: [
        {
            label: "I.T Contractor",
            image: "/contracts/constructor.svg",
            value: "contractor"
        },
        {
            label: "Content Writer",
            value: "content-writer",
            image: "/contracts/content_writer.svg",
        },
        {
            label: "Accountancy",
            value: "accountancy",
            image: "/contracts/accountancy.svg",
        },
        {
            label: "Banking",
            value: "banking",
            image: "/contracts/banking.svg",
        },
        {
            label: "Digital & Creative",
            value: "digital-creative",
            image: "/contracts/digital.svg",
        },
        {
            label: "Marketing & PR",
            value: "marketing-pr",
            image: "/contracts/banking.svg",
        },
        {
            label: "Supply Chain",
            value: "supply-chain",
            image: "/contracts/banking.svg",
        },
        {
            label: "Healthcare",
            value: "healthcare",
            image: "/contracts/accountancy.svg",
        },
        {
            label: "Education",
            value: "education",
            image: "/contracts/content_writer.svg",
        },
    ],
    contracts: [
        {
            id: "ct-001",
            company: "Meta",
            companyInitials: "ME",
            title: "Annual Cybersecurity & Threat Monitoring", 
            amount: "$120,000",
            amountPeriod: "Annual Contract",
            duration: "12 Months | Renewable",
            category: "I.T Contractor",
            tags: [
                { label: "Annual Contract", tone: "primary" },
                { label: "Verified", tone: "success" },
            ],
            summary:
                "Looking for an IT security partner to manage firewalls, intrusion detection, and ongoing risk assessments.",
            verified: true,
            ctaLabel: "Apply",
        },
        {
            id: "ct-002",
            company: "Intel",
            companyInitials: "IN",
            title: "Multi-Year Custom Software Development",
            amount: "$400,000",
            amountPeriod: "Year",
            duration: "3 Years",
            category: "I.T Contractor",
            tags: [{ label: "Long-Term", tone: "primary" }],
            summary:
                "Searching for a reliable development partner for enterprise-grade software solutions.",
            verified: false,
            ctaLabel: "Apply",
        },
        {
            id: "ct-003",
            company: "Plaid",
            companyInitials: "PL",
            title: "One-Time Supply of Laptops & Accessories",
            amount: "$42,000",
            amountPeriod: "One-Time Supply",
            duration: "2 Months",
            category: "Supply Chain",
            tags: [
                { label: "Bulk Order", tone: "primary" },
                { label: "Verified", tone: "success" },
            ],
            summary:
                "Looking for a supplier to deliver laptops and docking stations for a corporate office setup.",
            verified: true,
            ctaLabel: "Apply",
        },
        {
            id: "ct-004",
            company: "Merci",
            companyInitials: "MR",
            title: "Infrastructure Monitoring & Support",
            amount: "$9,000",
            amountPeriod: "Monthly",
            duration: "12 Months",
            category: "I.T Contractor",
            tags: [{ label: "Recurring Service", tone: "info" }],
            summary:
                "Seeking a partner to monitor cloud infrastructure with 99.9% uptime and proactive alerts.",
            verified: false,
            ctaLabel: "Apply",
        },
        {
            id: "ct-005",
            company: "Deloitte",
            companyInitials: "DL",
            title: "Quarterly Financial Audit Support",
            amount: "$60,000",
            amountPeriod: "Quarter",
            duration: "12 Months",
            category: "Accountancy",
            tags: [{ label: "Compliance", tone: "primary" }],
            summary:
                "Need experienced auditors to assist with quarterly reporting and regulatory compliance.",
            verified: true,
            ctaLabel: "Apply",
        },
        {
            id: "ct-006",
            company: "HSBC",
            companyInitials: "HS",
            title: "Retail Banking UX Copywriting",
            amount: "$18,000",
            amountPeriod: "Project",
            duration: "10 Weeks",
            category: "Content Writer",
            tags: [{ label: "UX Writing", tone: "primary" }],
            summary:
                "Seeking a writer to craft onboarding flows, error states, and transactional messaging.",
            verified: false,
            ctaLabel: "Apply",
        },
        {
            id: "ct-007",
            company: "Stripe",
            companyInitials: "ST",
            title: "Fraud Detection Model Tuning",
            amount: "$150,000",
            amountPeriod: "Annual Contract",
            duration: "6 Months",
            category: "Banking",
            tags: [
                { label: "Data Science", tone: "primary" },
                { label: "Verified", tone: "success" },
            ],
            summary:
                "Looking for specialists to tune fraud detection models using transaction signals.",
            verified: true,
            ctaLabel: "Apply",
        },
        {
            id: "ct-008",
            company: "A24",
            companyInitials: "A2",
            title: "Digital Campaign Creative Direction",
            amount: "$35,000",
            amountPeriod: "Project",
            duration: "8 Weeks",
            category: "Digital & Creative",
            tags: [{ label: "Creative", tone: "info" }],
            summary:
                "Need creative direction for a multi-channel film promotion campaign.",
            verified: false,
            ctaLabel: "Apply",
        },
        {
            id: "ct-009",
            company: "Unilever",
            companyInitials: "UN",
            title: "Global Brand Messaging Refresh",
            amount: "$95,000",
            amountPeriod: "Project",
            duration: "4 Months",
            category: "Marketing & PR",
            tags: [{ label: "Branding", tone: "primary" }],
            summary:
                "Looking for strategic messaging updates across global product lines.",
            verified: true,
            ctaLabel: "Apply",
        },
        {
            id: "ct-010",
            company: "FedEx",
            companyInitials: "FX",
            title: "Warehouse Automation Integration",
            amount: "$210,000",
            amountPeriod: "Project",
            duration: "5 Months",
            category: "Supply Chain",
            tags: [{ label: "Automation", tone: "info" }],
            summary:
                "Seeking integrators for warehouse automation and robotics deployment.",
            verified: false,
            ctaLabel: "Apply",
        },
        {
            id: "ct-011",
            company: "Cleveland Clinic",
            companyInitials: "CC",
            title: "Patient Outreach Content Series",
            amount: "$22,000",
            amountPeriod: "Project",
            duration: "6 Weeks",
            category: "Healthcare",
            tags: [{ label: "Content", tone: "primary" }],
            summary:
                "Need a multi-part content series for patient education and follow-up.",
            verified: true,
            ctaLabel: "Apply",
        },
        {
            id: "ct-012",
            company: "Coursera",
            companyInitials: "CO",
            title: "Instructional Design for Finance Track",
            amount: "$45,000",
            amountPeriod: "Course",
            duration: "10 Weeks",
            category: "Education",
            tags: [{ label: "Course Design", tone: "primary" }],
            summary:
                "Looking for instructional designers to build a finance-focused learning track.",
            verified: false,
            ctaLabel: "Apply",
        },
        {
            id: "ct-013",
            company: "Oracle",
            companyInitials: "OR",
            title: "Database Migration Assessment",
            amount: "$72,000",
            amountPeriod: "Project",
            duration: "3 Months",
            category: "I.T Contractor",
            tags: [{ label: "Migration", tone: "primary" }],
            summary:
                "Seeking consultants to assess migration readiness and risk mitigation.",
            verified: true,
            ctaLabel: "Apply",
        },
        {
            id: "ct-014",
            company: "Adobe",
            companyInitials: "AD",
            title: "Creative Cloud Tutorial Writing",
            amount: "$28,000",
            amountPeriod: "Project",
            duration: "9 Weeks",
            category: "Content Writer",
            tags: [{ label: "Tutorials", tone: "info" }],
            summary:
                "Need writers to create step-by-step tutorials for Creative Cloud tools.",
            verified: false,
            ctaLabel: "Apply",
        },
        {
            id: "ct-015",
            company: "EY",
            companyInitials: "EY",
            title: "Payroll Compliance Review",
            amount: "$38,000",
            amountPeriod: "Quarter",
            duration: "3 Months",
            category: "Accountancy",
            tags: [{ label: "Compliance", tone: "primary" }],
            summary:
                "Seeking specialists to audit payroll processes across multiple regions.",
            verified: true,
            ctaLabel: "Apply",
        },
        {
            id: "ct-016",
            company: "Goldman Sachs",
            companyInitials: "GS",
            title: "Risk Reporting Dashboard",
            amount: "$130,000",
            amountPeriod: "Project",
            duration: "4 Months",
            category: "Banking",
            tags: [{ label: "Analytics", tone: "primary" }],
            summary:
                "Looking for a team to build risk dashboards with real-time insights.",
            verified: false,
            ctaLabel: "Apply",
        },
        {
            id: "ct-017",
            company: "Spotify",
            companyInitials: "SP",
            title: "Audio Brand Campaign Toolkit",
            amount: "$52,000",
            amountPeriod: "Project",
            duration: "7 Weeks",
            category: "Digital & Creative",
            tags: [{ label: "Campaign", tone: "info" }],
            summary:
                "Need a creative partner to package assets for a global audio campaign.",
            verified: true,
            ctaLabel: "Apply",
        },
        {
            id: "ct-018",
            company: "Nike",
            companyInitials: "NK",
            title: "Athlete Storytelling Copy",
            amount: "$30,000",
            amountPeriod: "Project",
            duration: "5 Weeks",
            category: "Marketing & PR",
            tags: [{ label: "Storytelling", tone: "primary" }],
            summary:
                "Looking for writers to craft athlete profiles for global channels.",
            verified: true,
            ctaLabel: "Apply",
        },
        {
            id: "ct-019",
            company: "Pfizer",
            companyInitials: "PF",
            title: "Clinical Trial Recruitment Ads",
            amount: "$26,000",
            amountPeriod: "Project",
            duration: "6 Weeks",
            category: "Healthcare",
            tags: [{ label: "Campaign", tone: "info" }],
            summary:
                "Need ad copy and placements for a patient recruitment campaign.",
            verified: false,
            ctaLabel: "Apply",
        },
        {
            id: "ct-020",
            company: "Khan Academy",
            companyInitials: "KA",
            title: "Math Curriculum Update",
            amount: "$40,000",
            amountPeriod: "Project",
            duration: "8 Weeks",
            category: "Education",
            tags: [{ label: "Curriculum", tone: "primary" }],
            summary:
                "Seeking curriculum experts to refresh middle school math content.",
            verified: true,
            ctaLabel: "Apply",
        },
    ],
};

export async function POST() {
    const payloadWithImages = {
        ...contractsPayload,
        contracts: contractsPayload.contracts.map((contract) => ({
            ...contract,
            image: `/posts/post_${Math.floor(Math.random() * 4)}.png`,
        })),
    };

    return NextResponse.json(payloadWithImages);
}
